INSERT INTO BBY_5_user (ID, user_name, first_name, last_name, password, is_admin) VALUES (1, 'jparry', 'jim', 'parry', 'java', 0);
INSERT INTO BBY_5_user (ID, user_name, first_name, last_name, password, is_admin) VALUES (2, 'a-aron', 'arron', 'ferguson', 'a123', 0);
INSERT INTO BBY_5_user (ID, user_name, first_name, last_name, password, is_admin) VALUES (3, 'donna', 'donna', 'turner', 'a123', 0);
INSERT INTO BBY_5_user (ID, user_name, first_name, last_name, password, is_admin) VALUES (4, 'jason', 'jason', 'wilder', 'a123', 0);
INSERT INTO BBY_5_user (ID, user_name, first_name, last_name, password, is_admin) VALUES (5, 'keith', 'keith', 'tang', 'a123', 0);
INSERT INTO BBY_5_user (ID, user_name, first_name, last_name, password, is_admin) VALUES (6, 'arnold', 'arnold', 'schwarzenegger ', 'illbeback', 0);
INSERT INTO BBY_5_user (ID, user_name, first_name, last_name, password, is_admin) VALUES (7, 'sarvmr', 'Naz', 'Mohammadi', 'admin1', 1);
INSERT INTO BBY_5_user (user_name, first_name, last_name, password, is_admin) VALUES ('adult', 'Steve', 'Buscemi', 'sk8erboi', 0);
INSERT INTO BBY_5_user (user_name, first_name, last_name, password, is_admin) VALUES ('Nerdslayer0', 'Gabriel', 'Fairbairn', 'asdf', 1);

INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (1, 'Go postal', 'To suddenly behave in a very violent or angry way', 'The expression derives from a series of incidents from 1986 onward with USPS', 200, 'X');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (2, 'Salty', 'Angry, irritated or hostile', 'U.S. slang sense of "angry, irritated" is first attested 1938 (probably from similar use with regard to sailors, "tough, aggressive," attested by 1920)', 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (3, 'No Cap', 'Meant to convey authenticity and truth.', 'In the 1940s, according to Green''s Dictionary of Slang, to cap is evidenced as slang meaning "to surpass," connected to the ritualized insults of capping (1960s)', 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (4, 'thong', 'A light sandal with a thong between the big and second toe.', '"Thong" comes from words meaning "restraint," according to The Oxford English Dictionary, and was originally a narrow strip of leather used to secure something.', 200, 'B');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (5, 'Gas of a time', 'A popular slang term in the 1960s, a `gas` was any activity or event that was either fun or inspired you to laugh', 'The first is the expression `everything is gas and goiters,` which is first found in print used by Charles Dickens in 1839, meaning quite satisfactory', 200, 'B');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (6, 'Don`t flip your wig', "Use it to tell someone to calm down. ", 'Contrary to popular belief, it is not an old phrase, but was born in North America. The Oxford English Dictionary has the first print appearance listed in 1952.', 200, 'B');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (7, "Simp", "Short for simpleton and of showing excessive sympathy and attention toward another", "The 'New Partridge Dictionary of Slang and Unconventional English,' defines it as a shortened version of simpleton, so the phrase''s original meaning is rooted in calling someone stupid. The dictionary lists its first known usage as 1946, though it appeared in The New York Times as early as 1923", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (8, "Word", "You're right", "The phrase 'word' originally came from saying that your word is your bond, and it was shortened to just 'word.'", 200, 'X');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (9, "Wigging out", "Going crazy", "'Wigging out' is a variation of the older slang 'flip your wig' which was coined in 1952 or earlier", 200, 'X');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (10, "NOT", "psych!", "Popularized in North America in the 1990s by the Saturday Night Live sketch and subsequent film Wayne''s World, 'not' was selected as the 1992 Word of the Year by the American Dialect Society.", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (11, "Gettin' Jiggy", "Dance like no one is watching", "This 90s phrase came from the popular music video by Will Smith, Gettin' Jiggy With It.", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (12, "Fire", "Really cool and amazing", "It appears that the related terms lit and fire developed their current slang connotations of hot, cool, excellent during the ‘90s. The use of the fire emoji in text messages probably contributed to their diffusion", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (13, "Groovy", "Really cool and amazing", "Refering to music that's swinning, tight, funcky, in the pocket", 200, 'B');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (14, "Respek", "Respect", "First introduced into the lexicon in 2016 by rapper Birdman during rap radio show", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (15, "Adulting", "Engaging in an activity or behavior that involves responsibility or decision-making", "In the '80s, 'adulting' was used, according to Merriam-Webster, 'as a jocular verbal form of the noun adultery'", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (16, "Cancelled", "Rejected, deleted, cut out of your life", "The term has been credited to users of Twitter, where it has been used as a hashtag. As troubling information comes to light regarding celebrities who were once popular, —so come calls to cancel such figures", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (17, "Low key", "Describe something you're doing on the down-low, understatedly or secretly", "Musical origins, characterizing something has having a deeper, more muted, or darker tonal register.", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (18, "Draking", "Too emotional, revealing anxieties and insecurities", "Name of popular rapper Drake", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (19, "Thirst trap", "Thirsty or being thirsty", "The term thirst trap emerged on Twitter and Urban Dictionary in 2011, around the same time as the rise of Snapchat, Instagram, and online dating apps such as Tinder. In 2011, it was defined by Urban Dictionary as 'any statement used to intentionally create attention or thirst'", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (20, "It me", "This represents exactly how I feel", "One of many phrases that spread through online culture, usually used with a meme", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (21, "Bouta", "I am about to", "Likely originated from rap or song-writing as a means to shorten the phrase 'about to' to improve flow, that caught on in colloquial slang", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (22, "Clap back", "Respond to an insult with", "The term derives from a 2003 song by Ja Rule, appropriately titled 'Clap Back.' The phrase is the meat of the hook ('Clap back, we gon' clap back'), which answers what Ja Rule and his crew will do to rappers who disrespect them.", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (23, "Blessed", "Divinely or supremely favored", "Past-participle adjective from bless", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (24, "GRWM", "Get ready with me", "GRWM (full form: Get Ready With Me) is a film in which individuals videotape every step of their morning, evening, and ECT routine", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (25, "Bae", "Before anyone else", "It usually refers to a person's romantic partner, especially a boyfriend or girlfriend. It came into widespread use around 2013 and 2014 through social media and hip-hop and R&B lyrics", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (26, "Beat", "The verb refers to the application of one’s makeup. As an adjective beat means someone either applied their makeup well, or just applied a lot of it", "Mainly from British origins", 200, 'X');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (27, "Moo juice", "Milk", "From moo ('noise made by a cow') + juice ('extracted liquid')", 200, 'B');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (28, "Pressed", "To be very annoyed or mad", "Term originated on TikTok", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (29, "Big mad", "Extreme anger in a situation", "Big mad arose in popularity in 2017 along with 'big yikes,' which is an exaggeration of 'yikes.'", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (30, "Catch these hands", "To start a fight.", "'Catch these hands' and 'get these hands' are the catchphrases of Braun Strowman, a WWE wrestler and former strongman", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (31, "Go off", "To drone on about a topic, or ramble", "Starting in the 16th century, to go off meant to explode in a decisive spurt of energy.", 200, 'X');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (32, "FYP", "FYP stands for the 'For You' page on the massively popular short video app, TikTok", "Even though many apps now have a landing page with recommendations, FYP is commonly associated as originating from TikTok", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (33, "BOP", "When a song or album is exceptionally good", "You can also use bop to mean bebop, the fast-tempo jazz that became popular in the 1940s, after the swing era", 200, 'X');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (34, "GOAT", "The Greates of All Time", "Some one incredible ", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (35, "GUAP", "Money, and lots of it", "No history", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (36, "Mood", "Used to express that something is relatable. Similar to 'Same,' but 'Mood' became more common around 2016", "No history", 200, '');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (37, "FOMO", "Fear of missing out", "No history", 200, 'X');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (38, "Stan", "Obsessed but not in a creepy way", "Combination of 'stalker and 'fan'", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (39, "Fam", "Family", "It can be used to describe your friends", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (40, "Smol", "Something extremely small and cute", "No history", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (41, "Take the L", "Stands for 'Take the loss'", "No history", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (42, "Bet", "A strong confirmation, as in 'I am willing to bet on it'", "No history", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (43, "Lit", "Descriptor for something that is really good, intense, fun, or exciting", "'Lit' has been a slang term meaning 'intoxicated' for over a century. More recently, it has acquired the meaning 'exciting,'' as well as a broader meaning along the lines of 'excellent.'", 200, '');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (44, "Troll", "A person who deliberately makes random unsolicited and/or controversial comments on internet forums with the intent to provoke an emotional reaction", "The word evokes the trolls of Scandinavian folklore and children's tales: antisocial, quarrelsome and slow-witted creatures which make life difficult for travelers", 200, '');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (45, "ASL", "An abbreviation that stands for 'as hell,' which is used on TikTok, Twitter, and Instagram", "From TikTok, but may also mean other things", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (46, "Swol", "Swol, often spelled 'Swole', or 'Swohl' is a colloquial term for 'swollen.' Swol is a slang name that refers to someone who is highly muscular and well-built", "From gym-culture", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (47, "Cat", "Verb: To hoist an anchor to (the cathead)", "Sailor slang", 200, 'B');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (48, "Vibe check", "To check someone's energy or mood", "It's supposed to be a pleasant experience, like a check-in from a friend", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (49, "Scratch", "Money, funds", "A 1915 dictionary of criminal slang lists 'scratch' as a word used for money by 'literate criminals.'", 200, 'B');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (50, "Kiki", "A social gathering, usually for the purpose of casually “kicking back,” gossiping, and sharing stories", "It is historically connected to LGBTQ communities. Alternatively, kiki is also the name of a ballroom drag subculture that celebrates gender nonconformity, racial diversity, and sexual openness", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (51, "Lewk", "A variation of 'look,' a signature physical trait, or a specially and carefully constructed outfit or appearance", "Goreski made lewk part of his signature vocabulary on the The Rachel Zoe Project, using the word frequently on his own Twitter during his stint on the show, which he left in 2010", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (52, "Slaps", "To be excellent or amazing", "Slaps was an adjective for 'first-rate' in the mid-1800s and an adverb, meaning 'excellently,' even earlier, in the mid-1700s", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (53, "Slay", "To kill it - emphasized", "In 2016, Beyoncé took slay mainstream. She commanded her ladies to get in formation and slay", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (54, "Iykyk", "If you know you know", "Abbreviation", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (55, "Karen", "Pejorative term for a white woman perceived as entitled or demanding beyond the scope of what is normal", "One explanation is that it comes from the character Karen in the 2004 film Mean Girls, who’s the subject of the popular quote: 'Oh my God, Karen, you can’t just ask someone why they’re white'", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (56, "Simp", "Too attentive and submissive to women", "Term is degrading to women and a way of bullying men in 1987", 200, 'X');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (57, "Receipts", "'Proof' or 'evidence,' often used to call out someone for lying or to show someone is being genuine", "One of the first prominent uses of receipts came in a 2002 interview of singer Whitney Houston by Diane Sawyer for ABC. Sawyer brought up the topic of recent tabloid headlines that accused Houston of buying large amounts of crack cocaine. Houston denied these accusations and demanded proof: 'I want to see the receipts.'", 200, 'Y');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (58, "Sus", "Suspicious", "Originated from chiefly British Slang.", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (59, "Kicks", "Another word for shoes", "The Oxford English Dictionary dates it to 1904", 200, 'B');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (60, "Dad", "A way to express your love and affection for them or some aspect of their personality", "'it basically jokingly means 'adopt me/be my second mom/I think of you as a mother figure/you are so epic.' - Lorde (singer), 2015'", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (61, "TBH", "To be honest", "It's an initialism that gained traction in the late 90s or early 2000s, and its origins are closely associated with internet forums, internet relay chat (IRC), and text-message culture", 200, 'X');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (62, "Cheugy", "A slang adjective mocking someone or something as 'uncool'—they are out of touch with current trends or trying too hard to be trendy", "According to an April 2021 article in The New York Times written by Taylor Lorenz, the term cheugy was coined in 2013 by Gaby Rasson, a Beverly Hills High School student, who used it to describe 'people who were slightly off trend'", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (63, "Zaddy", "A sexually attractive man, especially an older one who is fashionable or charismatic.", "From z- (as an intensifier) + daddy (perhaps from sugar daddy) - Oxford Language Dictionary", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (64, "Yeet", "A powerful throw", "Originating and coined in 1998 by British presenter Jeremy Clarkson, but popularized by a 2014 video uploaded on Vine", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (65, "Glow up", "A positive personal transformation, typically one involving significant changes in appearance and style and often also growth in confidence and maturity", "The phrase was popularized (and may have been originated) by rapper Chief Keef, who used the term (spelled glo up—now a common alternate spelling) to refer to a positive improvement in his 2013 song 'Gotta Glo Up One Day.'", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (66, "I'm dead", "Find someone hilarious", "We can find ded for dead, as in the humorous exaggeration I’m dead in response to something extremely funny or frustrating, by the 2000s, including on Urban Dictionary by 2003", 200, 'Z');
INSERT INTO BBY_5_master (word_ID, phrase, meaning, history, value, generation) VALUES (67, "Gas", "An activity or event that is fun or insipered to laugh", "A popular slang term in the 1960s", 200, 'B');


INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(1, 2, 3, 0, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(1, 3, 0, 1, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(1, 4, 3, 3, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(1, 6, 6, 1, 0);

INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 13, 0, 2, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 65, 0, 2, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 64, 0, 7, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 52, 0, 10, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 22, 1, 9, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 55, 1, 16, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 31, 2, 1, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 32, 2, 4, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 57, 2, 19, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 53, 3, 12, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 54, 3, 14, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 35, 4, 1, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 34, 4, 1, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 40, 4, 8, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 2, 4, 10, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 33, 5, 0, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 17, 6, 7, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 51, 6, 7, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 41, 7, 1, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 19, 7, 5, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 7, 7, 16, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 58, 7, 16, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 29, 8, 13, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 50, 9, 7, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 59, 9, 12, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 44, 10, 3, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 28, 10, 11, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 48, 11, 7, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 24, 11, 10, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 66, 11, 15, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 67, 11, 10, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 25, 12, 9, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 26, 12, 9, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 63, 12, 17, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 43, 13, 3, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 23, 13, 7, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 45, 14, 1, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 46, 14, 2, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 30, 15, 4, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 47, 15, 4, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 3, 16, 1, 0);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 60, 17, 9, 1);
INSERT INTO BBY_5_crossword(crossword_id, word_id, row_num, col, vertical) VALUES(2, 49, 18, 6, 0);

INSERT INTO BBY_5_item (ID, name, description, price, type) VALUES (1, 'B upgrade coupon', 'Upgrades your B title by 1 level.', 2000, 'B');
INSERT INTO BBY_5_item (ID, name, description, price, type) VALUES (2, 'X upgrade coupon', 'Upgrades your X title by 1 level.', 2000, 'X');
INSERT INTO BBY_5_item (ID, name, description, price, type) VALUES (3, 'Y upgrade coupon', 'Upgrades your Y title by 1 level.', 2000, 'Y');
INSERT INTO BBY_5_item (ID, name, description, price, type) VALUES (4, 'Z upgrade coupon', 'Upgrades your Z title by 1 level.', 2000, 'Z');

